# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/" # Adjust if your composer.json is in a subdirectory
    schedule:
      interval: "weekly" # Options: daily, weekly, monthly
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all" # or "direct"/"indirect"
    commit-message:
      prefix: "chore"
      include: "scope"